### ISSUE TITLE
What does your mean about "long-tail entities" in your paper

### ISSUE THREAD

**Issue by zhangzhaoxuan** [Neph0s/LMKE#11]

**Comment by qiucy23** [comment]
I have same ques.

**Comment by Neph0s** [comment]
> However, real-world KGs are widely observed to have a
right-skewed degree distribution, i.e., degrees of entities approximately follow the power-law distribution that forms a
long tail, as is illustrated in Fig.1.

In KGC, long-tail entities are equal to entities with very few triples.
