### ISSUE TITLE
请问论文中的结果是哪一项呢

### ISSUE THREAD

**Issue by passermyh** [Neph0s/LMKE#7]
![QQ截图20230412112542](https://user-images.githubusercontent.com/71198047/231341771-4eb1b9bf-ff15-42dc-aa40-795c108667c1.png)
您好，我的导师要求阅读您的工作并进行汇报，但因为我的学习经验不足，对于您的结果有一个很简单的疑问，您给出了四个结果，raw head，fil head，raw tail,fil tail，请问哪一项是对应论文中的table2中的结果呢

**Comment by Neph0s** [comment]
是filter head 和tail的平均
